SRC = *.c\
SRC = *.c\

INC = *.h\

all: $(SRC)
	gcc $(SRC) $(INC) -o a.out

run:
	./a.out

clean:
	rm -rf *.out *.o
INC = *.h\

all: $(SRC)
	gcc $(SRC) $(INC) -o a.out

run:
	./a.out

clean:
	rm -rf *.out *.o
